version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Restore Maven Cache
          command: |
            mkdir -p ~/.m2
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test

workflows:
  maven-build:
    jobs:
      - build-and-test
