version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Official CircleCI OpenJDK 17 image
    working_directory: ~/repo/hello-world  # Set your working directory to hello-world
    steps:
      - checkout  # Checkout your code
      - run:
          name: Build with Maven
          command: mvn clean package -X  # Run your Maven build with debug output

workflows:
  build-and-test:
    jobs:
      - build
